src/Entity/Article.php
<?php

namespace App\Entity;

use App\Repository\ArticleRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\Criteria;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\ORM\Mapping\Table;
use Gedmo\Mapping\Annotation as Gedmo;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Validator\Context\ExecutionContextInterface;

/**
 * @Table(name="article", indexes={@ORM\Index(name="fk_author_idx", columns={"author_id"})})
 * @ORM\Entity(repositoryClass=ArticleRepository::class )
 */
class Article
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank()
     */
    private $title;

    /**
     * @ORM\Column(type="string", length=255)
     * @Gedmo\Slug(fields={"title"})
     */
    private $slug;

    /**
     * @ORM\Column(type="text")
     */
    private $content;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $publishedAt;

    /**
     * @var User
     *
     * @ORM\ManyToOne(targetEntity="App\Entity\User")
     * @ORM\JoinColumns({
     *   @ORM\JoinColumn(name="author_id", referencedColumnName="id")
     * })
     */
    private $author;

    /**
     * @ORM\Column(type="integer")
     */
    private $heartCount = 0;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $imageFilename;

    /**
     * @ORM\OneToMany(targetEntity=Comment::class, mappedBy="article")
     */
    private $comments;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $location;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $specificLocationName;

    public function __construct()
    {
        $this->comments = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getPublishedAt(): ?\DateTimeInterface
    {
        return $this->publishedAt;
    }

    public function setPublishedAt(?\DateTimeInterface $publishedAt): self
    {
        $this->publishedAt = $publishedAt;

        return $this;
    }

    public function isPublished(): bool
    {
        return $this->publishedAt !== null;
    }

    public function getAuthor(): ?User
    {
        return $this->author;
    }

    public function setAuthor(User $author): self
    {
        $this->author = $author;

        return $this;
    }

    public function getHeartCount(): ?int
    {
        return $this->heartCount;
    }

    public function setHeartCount(int $heartCount): self
    {
        $this->heartCount = $heartCount;

        return $this;
    }

    public function getImageFilename(): ?string
    {
        return $this->imageFilename;
    }

    public function setImageFilename(?string $imageFilename): self
    {
        if (!is_null($imageFilename)) {
            $this->imageFilename = $imageFilename;
        }
        return $this;
    }

    //funksion per te marre image path te postimit
    public function getImagePath()
    {
        return 'test/images/' . $this->getImageFilename();
    }

    public function incrementHeartCount(): self
    {
        $this->heartCount = $this->heartCount + 1;
        return $this;
    }

    /**
     * @return Collection|Comment[]
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    /**
     * @return Collection|Comment[]
     */
    public function getNonDeletedComments(): Collection
    {
        //only for arrayCollection
        $criteria = ArticleRepository::createNonDeletedCriteria();
        return $this->comments->matching($criteria);
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setArticle($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->removeElement($comment)) {
            // set the owning side to null (unless already changed)
            if ($comment->getArticle() === $this) {
                $comment->setArticle(null);
            }
        }

        return $this;
    }
//    /**
//     * @Assert\Callback
//     */
//    public function validate(ExecutionContextInterface $context, $payload)
//    {
//
//    }

    public function getLocation(): ?string
    {
        return $this->location;
    }

    public function setLocation(?string $location): self
    {
        $this->location = $location;

        return $this;
    }

    public function getSpecificLocationName(): ?string
    {
        return $this->specificLocationName;
    }

    public function setSpecificLocationName(?string $specificLocationName): self
    {
        $this->specificLocationName = $specificLocationName;
        return $this;
    }
}

src/Controller/ArticleController.php
<?php


namespace App\Controller;


use App\Entity\Article;
use App\Repository\CommentRepository;
use Doctrine\ORM\EntityManagerInterface;

use Psr\Log\LoggerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;

class ArticleController extends AbstractController
{
    /**
     * @Route("/", name="homepage")
     */
    public function homepage(EntityManagerInterface $em){
        $rep = $em->getRepository(Article::class);
        $articles = $rep->findAllPublishedByNewest();
        return $this->render('articles/homepage.html.twig',[
            'articles'=>$articles,
        ]);
    }
    /**
     * @Route("/news/{slug}", name="article_show")
     */
    public function show($slug){

        /** @var Article $article */
        $article = $this->getDoctrine()->getRepository(Article::class)->findOneBy(['slug'=>$slug]);
        if(!$article){
            throw $this->createNotFoundException(sprintf('No article found with this slug "%s" ',$slug));
        }
//        $comments = $commentRepository->findBy(['article'=>$article]);
//        $comments = $article->getComments();
//        foreach ($comments as $comment){
//            dd($comment);
//        }
        return $this->render('articles/show.html.twig', [
            'article'=>$article,
        ]);
    }
    /**
     * @Route("/news/{slug}/heart", name="article_toggle_heart", methods={"POST"})
     */
    public function toggleArticleHeart(Article $article, LoggerInterface $logger, EntityManagerInterface $entityManager){
        $article->incrementHeartCount();
        $entityManager->flush();
        $logger->info('hearted');
        return new JsonResponse(['hearts'=>$article->getHeartCount()]);
    }

}

templates/articles/homepage.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <div class="container">
        <div class="row">

            <!-- Article List -->

            <div class="col-sm-12 col-md-8">

                <!-- H1 Article -->
                <a class="main-article-link" href="#">
                    <div class="main-article mb-5 pb-3">
                        <img src="{{ asset('test/images/meteor-shower.jpg') }}" alt="meteor shower">
                        <h1 class="text-center mt-2">Ursid Meteor Shower: <br>Healthier than a regular shower?</h1>
                    </div>
                </a>

                <!-- Supporting Articles -->
                {% for article in articles %}
                <div class="article-container my-1">
                    <a href="{{ path('article_show', {slug:article.slug}) }}">
                        <img class="article-img" src="{{ asset(article.imagePath) }}">
                        <div class="article-title d-inline-block pl-3 align-middle">
                            <span>{{ article.title }}</span>
                            <small>({{ article.nonDeletedComments|length }} comments)</small>
                            <br>
                            <span class="align-left article-details"><img class="article-author-img rounded-circle" src="{{ asset('test/images/alien-profile.png') }}"> {{ article.author }} </span>
                            <span class="pl-5 article-details float-right"> {{ article.publishedAt ? article.publishedAt|ago : 'no data' }}</span>
                        </div>
                    </a>
                </div>

                {% endfor %}
            </div>
            <!-- Right bar ad space -->


            <div class="col-sm-12 col-md-4 text-center">
                <div class="ad-space mx-auto mt-1 pb-2 pt-2">
                    <img class="advertisement-img" src="{{ asset('test/images/space-ice.png') }}">
                    <p><span class="advertisement-text">New:</span> Space Ice Cream!</p>
                    <button class="btn btn-info">Buy Now!</button>
                </div>

                <div class="quote-space pb-2 pt-2 px-5">
                    <h3 class="text-center pb-3">Trending Quotes</h3>
                    <p><i class="fa fa-comment"></i> "Our two greatest problems are gravity and paperwork. We can lick gravity, but sometimes the paperwork is overwhelming." <br>— <a href="https://en.wikipedia.org/wiki/Wernher_von_Braun">Wernher von Braun, Rocket Engineer</a></p>

                    <p class="pt-4"><i class="fa fa-comment"></i> "Let's face it, space is a risky business. I always considered every launch a barely controlled explosion." <br>— <a href="https://en.wikipedia.org/wiki/Aaron_Cohen_(Deputy_NASA_administrator)">Aaron Cohen, NASA Administrator</a></p>

                    <p class="pt-4"><i class="fa fa-comment"></i> "If offered a seat on a rocket ship, don't ask what seat. Just get on."<br>— <a href="https://en.wikipedia.org/wiki/Christa_McAuliffe">Christa McAuliffe, Challenger Astronaut</a>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/articles/show.html.twig
{% extends('base.html.twig') %}
{% block title %}Read {{ article.title }} {% endblock %}
{% block body %}
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <div class="show-article-container p-3 mt-4">
                    <div class="row">
                        <div class="col-sm-12">
                            <img class="show-article-img" src="{{ asset(article.imagePath) }}">
                            <div class="show-article-title-container d-inline-block pl-3 align-middle">
                                <span class="show-article-title ">{{ article.title }}</span>
                                <br>
                                <span class="align-left article-details"><img class="article-author-img rounded-circle" src="{{ asset('/firstsymfony-master/public/test/images/alien-profile.png') }}"> {{ article.author }} </span>
                                <span class="pl-2 article-details">
                                    {{ article.publishedAt ? article.publishedAt|ago : 'no data' }}
                                </span>
                                <span class="pl-2 article-details">
                                    <span class="js-like-article-count">{{ article.heartCount }}</span>
                                    <a href="{{ path('article_toggle_heart', {slug:article.slug}) }}" class="fa fa-heart-o like-article js-like-article"></a>
                                </span>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-sm-12">
                            <div class="article-text">
                                {{ article.content }}
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-sm-12">
                            <p class="share-icons mb-5"><span class="pr-1">Share:</span> <i class="pr-1 fa fa-facebook-square"></i><i class="pr-1 fa fa-twitter-square"></i><i class="pr-1 fa fa-reddit-square"></i><i class="pr-1 fa fa-share-alt-square"></i></p>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-sm-12">
                            <h3><i class="pr-3 fa fa-comment"></i>{{ article.nonDeletedComments|length }} Comments</h3>
                            <hr>

                            <div class="row mb-5">
                                <div class="col-sm-12">
                                    <img class="comment-img rounded-circle" src="{{ asset('/firstsymfony-master/public/test/images/astronaut-profile.png') }}">
                                    <div class="comment-container d-inline-block pl-3 align-top">
                                        <span class="commenter-name">Amy Oort</span>
                                        <div class="form-group">
                                            <textarea class="form-control comment-form" id="articleText" rows="1"></textarea>
                                        </div>
                                        <button type="submit" class="btn btn-info">Comment</button>
                                    </div>
                                </div>
                            </div>
                            {% for comment in article.nonDeletedComments %}
                            <div class="row">
                                <div class="col-sm-12">
                                    <img class="comment-img rounded-circle" src="{{ asset('/firstsymfony-master/public/test/images/alien-profile.png') }}">
                                    <div class="comment-container d-inline-block pl-3 align-top">
                                        <span class="commenter-name">{{ comment.authorName }}</span>
                                        {% if comment.isDeleted %}
                                            <span class="fa fa-close"></span>deleted
                                        {% endif %}
                                        <br>
                                        <span class="comment">{{ comment.message}}</span>
                                        <p><a href="#">Reply</a></p>
                                    </div>
                                </div>
                            </div>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block javascripts %}
    {{  parent() }}
{#    //parent perdoret per te mos bere override tek pareent template js files#}
    <script src="{{ asset('test/js/article_show.js') }}"></script>
{% endblock %}